"""time to 'now()'

Revision ID: 0548f090a331
Revises: 702a0d27a30c
Create Date: 2023-02-06 21:06:21.623422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0548f090a331'
down_revision = '702a0d27a30c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
