"""add is_active

Revision ID: 508bc2403e4a
Revises: ccb15e96d6e0
Create Date: 2022-12-01 23:57:52.759033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508bc2403e4a'
down_revision = 'ccb15e96d6e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
