"""fix board default for not nullable

Revision ID: a347f3ec950e
Revises: 5063f234c142
Create Date: 2023-01-17 14:29:45.272000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a347f3ec950e'
down_revision = '5063f234c142'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'created_at', server_default=str(sa.func.now()))
    op.alter_column('board', 'updated_at', server_default=str(sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
