"""initial

Revision ID: bdf786ffd581
Revises: 
Create Date: 2023-01-09 16:55:37.196303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf786ffd581'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sns_sub', sa.String(length=60), nullable=True),
    sa.Column('login_type', sa.Enum('email', 'naver', 'google', 'apple', name='logintype'), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('picture_32', sa.String(length=255), nullable=True),
    sa.Column('picture_96', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), server_default='ㅇㅇ', nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='roletype'), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_type', 'email', name='type_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
