"""add board.py

Revision ID: d4794532ce03
Revises: d88a9ef856be
Create Date: 2022-12-13 21:24:30.078137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4794532ce03'
down_revision = 'd88a9ef856be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
