"""add sns sub

Revision ID: d88a9ef856be
Revises: 508bc2403e4a
Create Date: 2022-12-06 22:21:22.000199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88a9ef856be'
down_revision = '508bc2403e4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sns_sub', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sns_sub')
    # ### end Alembic commands ###
