"""change datetime default

Revision ID: db300e70a36f
Revises: 702a0d27a30c
Create Date: 2023-02-03 08:27:23.491763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db300e70a36f'
down_revision = '702a0d27a30c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at', server_default=sa.text("NOW() AT TIME ZONE 'UTC+9'"))
    op.alter_column('users', 'updated_at', server_default=sa.text("NOW() AT TIME ZONE 'UTC+9'"))
    op.alter_column('board', 'created_at', server_default=sa.text("NOW() AT TIME ZONE 'UTC+9'"))
    op.alter_column('board', 'updated_at', server_default=sa.text("NOW() AT TIME ZONE 'UTC+9'"))
    op.alter_column('comment', 'created_at', server_default=sa.text("NOW() AT TIME ZONE 'UTC+9'"))
    op.alter_column('comment', 'updated_at', server_default=sa.text("NOW() AT TIME ZONE 'UTC+9'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at', server_default=sa.text("NOW() AT TIME ZONE 'UTC'"))
    op.alter_column('users', 'updated_at', server_default=sa.text("NOW() AT TIME ZONE 'UTC'"))
    op.alter_column('board', 'created_at', server_default=sa.text("NOW() AT TIME ZONE 'UTC'"))
    op.alter_column('board', 'updated_at', server_default=sa.text("NOW() AT TIME ZONE 'UTC'"))
    op.alter_column('comment', 'created_at', server_default=sa.text("NOW() AT TIME ZONE 'UTC'"))
    op.alter_column('comment', 'updated_at', server_default=sa.text("NOW() AT TIME ZONE 'UTC'"))
    # ### end Alembic commands ###
