"""fix again for board server_default

Revision ID: db3b140dc939
Revises: 5063f234c142
Create Date: 2023-01-18 08:43:16.057435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3b140dc939'
down_revision = '5063f234c142'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'created_at', server_default=str(sa.sql.func.now()))
    op.alter_column('board', 'updated_at', server_default=str(sa.sql.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
